;-------------------------------------------------------------------------------
;		CONFIGURACIÓN GENERAL DEL PROYECTO 
;------------------------------------------------------------------------------- 
    
#include "Pines_config_18f45k20.inc"  ; Incluye configuración de pines
#include "Macros.inc"		  ; Incluye las Macros disponibles  
#include "Vectores_config.inc"	  ; Inclye el archivo declaración de vectores de programa
#INCLUDE "P18F45K20.INC"          ; processor specific variable definitions
#define T0PLD (0EC78h) ;@8MHz produce 0.125uS a un prescaler 1:2


