;-------------------------------------------------------------------------------
;		CONFIGURACIÓN PROGRAMAS DELAY 
;------------------------------------------------------------------------------- 
    #define load_d1   0x11
Delay_ram udata	    ;configura la posición de almacenamiento de registros según convenga
d1 res 1	    ; Reseva 1 byte a el registro d1
d2 res 1	    ; Reseva 1 byte a el registro d2
d3 res 1	    ; Reseva 1 byte a el registro d3

