;-------------------------------------------------------------------------------
;		CONFIGURACIÓN Y DECLARACIÓN EN VARIABLE DE PINES
;-------------------------------------------------------------------------------    
    #define RAM0 0X00
 
    
      
    #define LED LATD,RD1
    #define LED_TRIS TRISD,RD1
    

    #define B0 LATB,RB0 
    #define B0_TRIS TRISB,RB0
    
    ;#define COUNTER1 .200    ; Contador interrupciones para overflow 5ms
    ;#define COUNTER2 .0	     ; Contador tiempo
    


 


